// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzK5K3Wu4PjxvPgbLDMOZmzFFBlfizfN0',
    appId: '1:698591410517:web:5f1dc526de0b3053be17dc',
    messagingSenderId: '698591410517',
    projectId: 'tuneup-3229c',
    authDomain: 'tuneup-3229c.firebaseapp.com',
    storageBucket: 'tuneup-3229c.firebasestorage.app',
    measurementId: 'G-DNZ9ZEY23W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrB5frIrG8_GPTZzkhLrw6qUQP3aDY6yU',
    appId: '1:698591410517:android:a1f1a965b622a888be17dc',
    messagingSenderId: '698591410517',
    projectId: 'tuneup-3229c',
    storageBucket: 'tuneup-3229c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFUIOKR4coyrQDQG0gNRor45ArMihUPdc',
    appId: '1:698591410517:ios:d12995dd6310e2f2be17dc',
    messagingSenderId: '698591410517',
    projectId: 'tuneup-3229c',
    storageBucket: 'tuneup-3229c.firebasestorage.app',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAFUIOKR4coyrQDQG0gNRor45ArMihUPdc',
    appId: '1:698591410517:ios:d12995dd6310e2f2be17dc',
    messagingSenderId: '698591410517',
    projectId: 'tuneup-3229c',
    storageBucket: 'tuneup-3229c.firebasestorage.app',
    iosBundleId: 'com.example.testDrive',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzK5K3Wu4PjxvPgbLDMOZmzFFBlfizfN0',
    appId: '1:698591410517:web:923c559a41a3edd9be17dc',
    messagingSenderId: '698591410517',
    projectId: 'tuneup-3229c',
    authDomain: 'tuneup-3229c.firebaseapp.com',
    storageBucket: 'tuneup-3229c.firebasestorage.app',
    measurementId: 'G-H5DW6F965R',
  );
}
